name: Check Proofs

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  check_proof:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t jasmin-xmss .

      - name: Check single/multi tree proof
        run: docker run --rm jasmin-xmss make -j$(nproc) -C proof/ check_xmss_xmssmt_proof
        