name: Check EasyCrypt Correctness Proof with EasyCrypt main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  check_correctness_proof_ec_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build --build-arg EASYCRYPT_RELEASE= -t jasmin-xmss .

      - name: Check correctness proofs
        run: docker run --rm jasmin-xmss make -C proof/ check_correctness_proof

