name: Compile Jasmin

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test_dir:
          - test/hash_address
          - test/hash
          - test/wots
          - test/treehash

    steps:
      - name: Check out code
        uses: actions/checkout@v4   

      - name: Build docker image
        run: docker build -t jasmin-xmss .

      - name: Compile ${{ matrix.test_dir }}
        run: docker run --rm jasmin-xmss make -C ${{ matrix.test_dir }}
