name: Compile Jasmin

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  compile_jasmin:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t jasmin-xmss .

      - name: Check correctness proofs
        run: docker run --rm jasmin-xmss make -C test/xmss/ asm

