name: Run tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t jasmin-xmss .

      - name: Run tests for hash address
        run: docker run --rm jasmin-xmss make -C test/hash_address/ run

      - name: Run tests for hash
        run: docker run --rm jasmin-xmss make -C test/hash/ run

      - name: Run tests for wots
        run: docker run --rm jasmin-xmss make -C test/wots/ run

